blank_issues_enabled: false
contact_links:
  - name: Discussoes
    url: https://github.com/AndreBFarias/FogStripper-Removedor-Background/discussions
    about: Use discussoes para perguntas gerais e ideias
